# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0.xci
# IP: The module: 'TopLevelDesign_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0.xci
# IP: The module: 'TopLevelDesign_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
