# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PBlock.xdc

# Block Designs: bd/TopLevelDesign/TopLevelDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign || ORIG_REF_NAME==TopLevelDesign} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_processing_system7_0_0/TopLevelDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_processing_system7_0_0 || ORIG_REF_NAME==TopLevelDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_axi_gpio_0_0 || ORIG_REF_NAME==TopLevelDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_ps7_0_axi_periph_0/TopLevelDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==TopLevelDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_rst_ps7_0_100M_0/TopLevelDesign_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==TopLevelDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_SimpleArithmeticAXI_0_0/TopLevelDesign_SimpleArithmeticAXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_SimpleArithmeticAXI_0_0 || ORIG_REF_NAME==TopLevelDesign_SimpleArithmeticAXI_0_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_xbar_0 || ORIG_REF_NAME==TopLevelDesign_xbar_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_auto_pc_0/TopLevelDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopLevelDesign_auto_pc_0 || ORIG_REF_NAME==TopLevelDesign_auto_pc_0} -quiet] -quiet

# XDC: bd/TopLevelDesign/TopLevelDesign_ooc.xdc
