# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.cache/wt [current_project]
set_property parent.project_path /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/tinytangent/ucore-plus-fpga/ip_repo/ReconfigurationTest_1.0
  /home/tinytangent/ucore-plus-fpga/ip_repo/ReconfigurableArithmeticAXI_1.0
  /home/tinytangent/ucore-plus-fpga/ip_repo/SimpleArithmeticAXI_1.0
} [current_project]
set_property ip_output_repo /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.runs/OpUnit_synth_1/OpUnit.dcp
set_property used_in_implementation false [get_files /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.runs/OpUnit_synth_1/OpUnit.dcp]
read_xdc hd_reconfig.xdc
set_property used_in_implementation false [get_files hd_reconfig.xdc]
read_vhdl -library xil_defaultlib {
  /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/new/OpUnitWrapper.vhd
  /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/imports/hdl/TopLevelDesign_wrapper.vhd
  /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/new/OpUnitAdd.vhd
  /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/new/OpUnitSub.vhd
}
add_files /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/TopLevelDesign.bd
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_processing_system7_0_0/TopLevelDesign_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_axi_gpio_0_0/TopLevelDesign_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_rst_ps7_0_100M_0/TopLevelDesign_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_rst_ps7_0_100M_0/TopLevelDesign_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_rst_ps7_0_100M_0/TopLevelDesign_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_auto_pc_0/TopLevelDesign_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/sources_1/bd/TopLevelDesign/TopLevelDesign_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/constrs_1/new/PBlock.xdc
set_property used_in_implementation false [get_files /home/tinytangent/ucore-plus-fpga/Simple_Arithmetic/Simple_Arithmetic.srcs/constrs_1/new/PBlock.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TopLevelDesign_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopLevelDesign_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopLevelDesign_wrapper_utilization_synth.rpt -pb TopLevelDesign_wrapper_utilization_synth.pb"
